### ISSUE TITLE
BBG Tickers with whitespaces properly not working with blp.bdib

### ISSUE THREAD

**Issue by choi300** [alpha-xone/xbbg#8]
There are some instruments whose BBG ticker has one or more white spaces within the name of tickers, such as Corn futures("C 1 Comdty") or Soybean Futures("S 1 Comdty"). If I add those kind of instrument's ticker into markets/assets.yml, simply blp.bdib function doesn't recognize them. I need to put trailing whitespace at the end of list items but when reading yml files, the function seem to ignores the trailing whitespace. In case of "S 1 Comdty", I tried putting "S " or S\ or S"\ " as below but any of those are not working. How can I insert tickers with whitespaces into markets/assets.yml?

```
Comdty:
  - tickers: [CL, "S ", XB, GC, PL, HO, NG, PA]
    exch: NYME
    freq: M
    is_fut: True

```

Error Messages are like this: 2019-11-25 15:44:24,982:xbbg.const.exch_info:ERROR:required exchange info cannot be found in S 1 Comdty ...
